### ISSUE TITLE
MQTT ring buffer should be protected in subscribe callbacks 

### ISSUE THREAD

**Issue by PhilDay-CT** [CHERIoT-Platform/network-stack#43]
The MQTT subscribe callback gets passed a reference to part of the receive buffer used by coreMQTT for incoming messages.  We should pass this as a read-only, non-capturable capabilty, since outside of the context of the callback it's content is not valid.

**Comment by hlef** [comment]
Oops, sounds right, looks like I missed this. I added it to my TODO list, but go ahead if you want to do the fix!

**Comment by hlef** [comment]
Note: I fixed this in my `hlefeuvre/bug-fixes` branch, which I will PR once the server API has been merged.

**Comment by hlef** [comment]
This was fixed as part of #46.
